openapi: 3.0.1
info:
  title: KYC (Know Your Customer)
  description: >-
    Antes de abrir uma conta de pagamento ou solicitar um cartão de crédito
    (pré-pago), conheça mais sobre o seu cliente.
  version: '1.0'
servers:
  - url: 'https://api.sandbox.bankly.com.br'
paths:
  '/document-analysis/{documentNumber}':
    get:
      tags:
        - Análise de documentos
      summary: |
        Obtenha o resultado da análise do documento.
      description: |
        <div class="bkly-ref-description">
          <p>Você pode solicitar mais de um resultado, informando os tokens correspondentes às análises solicitadas.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: kyc.document.read</span>
        </div>  
      operationId: GetDocumentAnalysis
      parameters:
        - $ref: '#/components/parameters/CustomerDocument'
        - $ref: '#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/ResultLevel'
        - $ref: '#/components/parameters/AnalysisToken'
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentAnalysisResponse'
              examples:
                Selfie:
                  $ref: '#/components/examples/Selfie'
                DocumentFront:
                  $ref: '#/components/examples/DocumentFront'
                DocumentBack:
                  $ref: '#/components/examples/DocumentBack'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      tags:
        - Análise de documentos
      summary: |
        Envie documentos (SELFIE, RG ou CNH) para análise.
      description: |
        <div class="bkly-ref-description">
          <p>Essa análise é um pré-requisito para fluxo de onboarding completo e atualização cadastral para clientes pessoa física ou pessoa jurídica.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: kyc.document.write</span>
        </div>  
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "A análise acontece de forma assíncrona, considere consultar o status da análise antes de avançar com as etapas do onboarding completo ou atualização cadastral."
        }
        [/block]
      operationId: UploadDocument
      parameters:
        - $ref: '#/components/parameters/CustomerDocument'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DocumentAnalysisForm'
            encoding:
              documentType:
                style: form
              documentSide:
                style: form
              image:
                style: form
      responses:
        '202':
          description: Requisição foi aceita e está sendo processada.
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadDocumentResponse'
              examples:
                analysIsTokenResponse:
                  value:
                    token: T42tcobk32rgiSGM23O6aDTFG6VhhKK4ZR
                  summary: Token da análise
        '400':
          $ref: '#/components/responses/400'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
      security:
        - Bearer: []
security:
  - Bearer: []
components:
  parameters:
    ApiVersion:
      name: api-version
      in: header
      description: Versão da API. Atualmente estamos na 1.0.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: 1
    CustomerDocument:
      name: documentNumber
      in: path
      description: Número do documento CPF do cliente. Informe somente os números.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/CustomerDocument'
    ResultLevel:
      name: resultLevel
      in: query
      description: Tipo de retorno da API (ONLY_STATUS ou DETAILED).
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/ResultLevel'
    AnalysisToken:
      name: token
      in: query
      description: Lista de tokens de análise do documento.
      required: false
      style: form
      explode: true
      schema:
        type: array
        description: Lista de tokens de análise do documento.
        nullable: true
        items:
          type: string
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          nullable: true
        propertyName:
          type: string
          nullable: true
        messages:
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Error'
        reference:
          type: integer
          format: int32
      additionalProperties: false
    CustomerDocument:
      type: string
      maxLength: 11
      minLength: 11
    DocumentType:
      type: string
      description: 'Tipo do documento (RG, CNH, SELFIE).'
      enum:
        - RG
        - CNH
        - SELFIE
    DocumentSide:
      type: string
      description: >-
        Lado do documento (FRONT ou BACK). Quando o tipo do documento for
        selfie, este parâmetro será desprezado.
      enum:
        - FRONT
        - BACK
    ResultLevel:
      type: string
      description: Tipo de retorno da API (ONLY_STATUS ou DETAILED).
      default: ONLY_STATUS
      enum:
        - ONLY_STATUS
        - DETAILED
    AnalysisStatus:
      type: string
      enum:
        - ANALYZING
        - PARTIALLY_ANALYZED
        - ANALYSIS_COMPLETED
        - UNEXPECTED_ERROR
    FaceMatchStatus:
      type: string
      enum:
        - HAS_FACE_MATCH
        - UNMATCHED_DOCUMENT
        - MANY_FACES_DETECTED
    FaceMatch:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/FaceMatchStatus'
        similarity:
          type: number
          format: double
          nullable: true
        confidence:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    FaceDetailsStatus:
      type: string
      enum:
        - DETECTED_FACE
        - MANY_FACES_DETECTED
        - COULD_NOT_DETECT_FACE
    AgeRange:
      type: object
      properties:
        low:
          type: integer
          format: int32
          nullable: true
        high:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    FacialDetail:
      type: object
      properties:
        value:
          type: object
          additionalProperties: false
          description: Tipo do detalhe facial identificado
          nullable: true
        confidence:
          type: number
          description: N�vel de confian�a do resultado
          format: float
          nullable: true
      additionalProperties: false
    FaceDetails:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/FaceDetailsStatus'
        confidence:
          type: number
          format: float
          nullable: true
        ageRange:
          $ref: '#/components/schemas/AgeRange'
        gender:
          $ref: '#/components/schemas/FacialDetail'
        sunglasses:
          $ref: '#/components/schemas/FacialDetail'
        eyesOpen:
          $ref: '#/components/schemas/FacialDetail'
        emotions:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/FacialDetail'
      additionalProperties: false
    OcrStatus:
      type: string
      enum:
        - DETECTED_DOCUMENT
        - NO_DOCUMENT_FOUND
        - NO_INFO_FOUND
    DocumentDetails:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/OcrStatus'
        identifiedDocumentType:
          type: string
          nullable: true
        idNumber:
          type: string
          nullable: true
        cpfNumber:
          type: string
          nullable: true
        birthDate:
          type: string
          nullable: true
        fatherName:
          type: string
          nullable: true
        motherName:
          type: string
          nullable: true
        registerName:
          type: string
          nullable: true
        validDate:
          type: string
          nullable: true
        driveLicenseCategory:
          type: string
          nullable: true
        driveLicenseNumber:
          type: string
          nullable: true
        driveLicenseFirstQualifyingDate:
          type: string
          nullable: true
        federativeUnit:
          type: string
          nullable: true
        issuedBy:
          type: string
          nullable: true
        issuePlace:
          type: string
          nullable: true
        issueDate:
          type: string
          nullable: true
      additionalProperties: false
    LivenessStatus:
      type: string
      enum:
        - LIVENESS_FOUND
        - NO_LIVENESS
        - COULD_NOT_DETECT_FACE
    Liveness:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/LivenessStatus'
        confidence:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    UploadDocumentResponse:
      type: object
      properties:
        token:
          type: string
          nullable: true
      additionalProperties: false
    DocumentAnalysisResponse:
      type: object
      properties:
        token:
          type: string
          nullable: true
        documentType:
          $ref: '#/components/schemas/DocumentType'
        documentSide:
          $ref: '#/components/schemas/DocumentSide'
        status:
          $ref: '#/components/schemas/AnalysisStatus'
        faceMatch:
          $ref: '#/components/schemas/FaceMatch'
        faceDetails:
          $ref: '#/components/schemas/FaceDetails'
        documentDetails:
          $ref: '#/components/schemas/DocumentDetails'
        liveness:
          $ref: '#/components/schemas/Liveness'
        analyzedAt:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    DocumentAnalysisForm:
      required:
        - documentType
        - documentSide
        - image
      type: object
      properties:
        documentType:
          $ref: '#/components/schemas/DocumentType'
        documentSide:
          $ref: '#/components/schemas/DocumentSide'
        image:
          type: string
          description: >-
            Arquivo da imagem. Não deve ser superior à 1 MB. A resolução deve
            ser compatível com VGA. [Saiba
            mais](https://en.wikipedia.org/wiki/Video_Graphics_Array).
          format: binary
          nullable: true
  headers:
    CorrelationId:
      description: Id correlação da operação requisitada.
      style: simple
      explode: false
      schema:
        type: string
    Location:
      description: Localização do recurso recém-criado ou em análise.
      style: simple
      explode: false
      schema:
        type: string
  responses:
    '202':
      description: Requisição foi aceita e está sendo processada.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
        Location:
          $ref: '#/components/headers/Location'
    '400':
      description: Há algum problema com a sua requisição.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/invalidParameterErrorResponse'
    '404':
      description: |
        Recurso não encontrado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
    '409':
      description: |
        A solicitação conflitou com o estado atual do recurso existente no
        servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '422':
      description: |
        A sintaxe da requisição esta correta, mas não foi possível processar
        devido uma regra de negócio.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '500':
      description: |
        Ocorreu algum erro inexperado no nosso servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT
  examples:
    invalidParameterErrorResponse:
      value:
        errors:
          - code: INVALID_PARAMETER
            propertyName: '{{propertyName}}'
            messages:
              - '{{"propertyName" error message}}'
      summary: Parametro inválido
    errorResponse:
      value:
        errors:
          - code: SOME_ERROR_CODE
            messages:
              - '{{Some error message}}'
      summary: Erro de negócio
    Selfie:
      value:
        - token: string
          documentType: SELFIE
          documentSide: FRONT
          status: ANALYSIS_COMPLETED
          liveness:
            status: LIVENESS_FOUND
            confidence: 1.9746
          faceDetails:
            status: DETECTED_FACE
            confidence: 99.99689
            ageRange:
              low: 18
              high: 23
            gender:
              value: Male
              confidence: 99.21723
            sunglasses:
              value: false
              confidence: 99.40401
            eyesOpen:
              value: false
              confidence: 57.259457
            emotions:
              - value: CALM
                confidence: 95.32976
              - value: SAD
                confidence: 2.078439
              - value: CONFUSED
                confidence: 0.9475501
              - value: ANGRY
                confidence: 0.6159508
              - value: SURPRISED
                confidence: 0.37119603
              - value: FEAR
                confidence: 0.24299896
              - value: HAPPY
                confidence: 0.20983662
              - value: DISGUSTED
                confidence: 0.20425977
          analyzedAt: '2021-08-31T21:20:58.754Z'
      summary: Selfie (do cliente ou representante legal)
    DocumentFront:
      value:
        - token: string
          documentType: RG
          documentSide: FRONT
          status: ANALYSIS_COMPLETED
          faceMatch:
            status: HAS_FACE_MATCH
            similarity: 99.98459
            confidence: 99.99835
          documentDetails:
            status: DETECTED_DOCUMENT
            identifiedDocumentType: RG
            idNumber: string
            cpfNumber: string
            birthDate: string
            fatherName: string
            motherName: string
            registerName: string
            validDate: string
            driveLicenseCategory: string
            driveLicenseNumber: string
            driveLicenseFirstQualifyingDate: string
            federativeUnit: string
            issuedBy: string
            issuePlace: string
            issueDate: string
          analyzedAt: '2021-08-31T21:20:58.754Z'
      summary: Frente do documento (o lado que tem foto)
    DocumentBack:
      value:
        - token: string
          documentType: RG
          documentSide: BACK
          status: ANALYSIS_COMPLETED
          documentDetails:
            status: DETECTED_DOCUMENT
            identifiedDocumentType: RG
            idNumber: string
            cpfNumber: string
            birthDate: string
            fatherName: string
            motherName: string
            registerName: string
            validDate: string
            driveLicenseCategory: string
            driveLicenseNumber: string
            driveLicenseFirstQualifyingDate: string
            federativeUnit: string
            issuedBy: string
            issuePlace: string
            issueDate: string
          analyzedAt: '2021-08-31T21:20:58.754Z'
      summary: Verso do documento (o lado que não tem foto)
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
