openapi: 3.0.1
info:
  title: Gestão de Contas
  description: Abra e gerencie contas de pagamento do seu cliente pessoa física ou jurídica.
  version: '1.0'
servers:
  - url: https://api.sandbox.bankly.com.br
paths:
  /accounts/{accountNumber}:
    get:
      tags:
        - Conta de pagamentos
      summary: Obtenha dados da conta de pagamentos.
      description: |
        <div class="bkly-ref-description">
          <p>Opcionalmente você pode obter o saldo desta conta.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.read</span>
        </div>  
      operationId: GetAccount
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/AccountNumber'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/IncludeBalance'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailedResponse'
              examples:
                  accountBasicExample:
                      $ref: '#/components/examples/accountBasicExample'
                  accountDetailedExample:
                      $ref: '#/components/examples/accountDetailedExample'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
  /customers/{documentNumber}/accounts:
    get:
      tags:
        - Conta pessoa física
      summary: Obtenha as contas de pagamento de um cliente.
      description: |
        <div class="bkly-ref-description">
          <p>Retornaremos uma lista com todas as contas desse cliente, independentemente de seus respectivos status.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.read</span>
        </div>
      operationId: GetPersonalAccounts
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/CustomerDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBasicResponse'
              examples:
                  listOfAccounts:
                    $ref: '#/components/examples/listOfAccounts'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
    post:
      tags:
        - Conta pessoa física
      summary: Crie uma conta de pagamentos pessoa física.
      description: |
        <div class="bkly-ref-description">
          <p>O cliente poderá ter até 5 contas de pagamento, no entanto é necessário ter o registro do titular (pessoa física) previamente aprovado.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.create</span>
        </div>
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Considere o uso do header ```Idempotency-Key``` afim de evitar criar contas indesejadas."
        }
        [/block]  
      operationId: CreatePersonalAccount
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/CustomerDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/IdempotencyKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Recurso criado com sucesso.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
            Location:
              $ref: 'http://localhost:3320/commons/components#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailedResponse'
              examples:
                  accountDetailedExample:
                      $ref: '#/components/examples/accountDetailedExample'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
  /business/{documentNumber}/accounts:
    get:
      tags:
        - Conta pessoa jurídica
      summary: Obtenha as contas de pagamento de uma empresa.
      description: |
          <div class="bkly-ref-description">
            <p>Retornaremos uma lista com todas as contas dessa empresa, independentemente de seus respectivos status.</p>
            <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.read</span>
          </div>  
      operationId: GetBusinessAccounts
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/BusinessDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBasicResponse'
              examples:
                  listOfAccounts:
                    $ref: '#/components/examples/listOfAccounts'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
    post:
      tags:
        - Conta pessoa jurídica
      summary: Crie uma conta de pagamentos para uma empresa (MEI, EI ou EIRELLI).
      description: |
        <div class="bkly-ref-description">
          <p>A empresa poderá ter até 5 contas de pagamento, no entanto é necessário ter o registro do titular (pessoa jurídica) previamente aprovado.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.create</span>
        </div>  
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Considere o uso do header ```Idempotency-Key``` afim de evitar criar contas indesejadas."
        }
        [/block] 
      operationId: CreateBusinessAccount
      parameters:
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/BusinessDocument'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/ApiVersion'
        - $ref: 'http://localhost:3320/commons/components#/components/parameters/IdempotencyKey' 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Recurso criado com sucesso.
          headers:
            x-bkly-correlation-id:
              $ref: 'http://localhost:3320/commons/components#/components/headers/CorrelationId'
            Location:
              $ref: 'http://localhost:3320/commons/components#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailedResponse'
              examples:
                  accountDetailedExample:
                      $ref: '#/components/examples/accountDetailedExample'
        '400':
          $ref: 'http://localhost:3320/commons/components#/components/responses/400'
        '403':
          $ref: 'http://localhost:3320/commons/components#/components/responses/403'
        '409':
          $ref: 'http://localhost:3320/commons/components#/components/responses/409'
        '422':
          $ref: 'http://localhost:3320/commons/components#/components/responses/422'
        '500':
          $ref: 'http://localhost:3320/commons/components#/components/responses/500'
  
security:
  - Bearer: []

components: 

  parameters:

    IncludeBalance:
      name: includeBalance
      in: query
      description: Inclua o saldo da conta na pesquisa.
      required: false
      style: form
      explode: true
      schema:
        type: boolean
        default: false
  
  schemas:
    
    Error:
      $ref: http://localhost:3320/commons/components#/components/schemas/ErrorResponse
    ErrorResponse:
      $ref: http://localhost:3320/commons/components#/components/schemas/Error
    
    Balance:
      description: Saldo da conta.
      type: object
      properties:
        amount:
          description: |
            Valor em decimal. Ex: 1.00.
          type: number
          format: double
        currency:
          description: |
            Moeda corrente. _Default: *BRL*_
          type: string
      additionalProperties: false

    SummarizedBalance:
      description: Saldo sumarizado da conta.
      type: object
      properties:
        inProcess:
          description: Saldo em processamento _(cash in)_.
          $ref: '#/components/schemas/Balance'
        available:
          description: Saldo disponível.
          $ref: '#/components/schemas/Balance'
        blocked:
          description: Saldo em bloqueio judicial.
          $ref: '#/components/schemas/Balance'
      additionalProperties: false

    AccountStatus:
      type: string
      description: |
        Status da conta.
        _(ACTIVE, CLOSED)_
      enum:
        - ACTIVE
        - CLOSED

    AccountType:
      type: string
      description: |
        Tipo da conta a ser criada. 
        _Default: **PAYMENT_ACCOUNT**_.
      default: PAYMENT_ACCOUNT
      enum:
        - PAYMENT_ACCOUNT

    CreateAccountRequest:
      type: object
      properties:
        accountType:
          $ref: '#/components/schemas/AccountType'
      additionalProperties: false

    AccountBasicResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/AccountStatus'
        branch:
          $ref: 'http://localhost:3320/commons/components#/components/schemas/BankBranch'
        number:
          $ref: 'http://localhost:3320/commons/components#/components/schemas/AccountNumber'
      additionalProperties: false

    AccountDetailedResponse:
      type: object
      properties:
        balance:
          $ref: '#/components/schemas/SummarizedBalance'
        status:
          $ref: '#/components/schemas/AccountStatus'
        branch:
          $ref: 'http://localhost:3320/commons/components#/components/schemas/BankBranch'
        number:
          $ref: 'http://localhost:3320/commons/components#/components/schemas/AccountNumber'
      additionalProperties: false
 

  examples:

    accountBasicExample:
      value:
        branch: '0001'  
        number: '123456'
        status: 'ACTIVE'
      summary: Conta de pagamento sem saldo

    accountDetailedExample:
      value:
        branch: '0001'  
        number: '123456'
        status: 'ACTIVE'
        balance: 
          available:
              amount: 0.00
              currency: 'BRL'
          inProcess:
              amount: 0.00
              currency: 'BRL'
          blocked:
              amount: 0.00
              currency: 'BRL'  
      summary: Conta de pagamento com saldo
      
    listOfAccounts:
      value:
        - number: '123456'
          branch: '0001'  
          status: 'ACTIVE'
        - number: '123'
          branch: '0001'  
          status: 'CLOSED'
      summary: Lista de contas de pagamento

x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl